backend:
  name: github
  repo: mbernardes19/portfolio

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: image, label: Image, widget: image}
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }